---
global:
  writeToFile: true
  metricsDirectory: /var/configs/metrics
  createTarball: true
  indexerConfig:
    enabled: false
    esServers: [http://elastic-elk.apps.rsevilla.kube-burner.com]
    insecureSkipVerify: true
    defaultIndex: kube-burner
    type: elastic
  measurements:
    - name: podLatency
      esIndex: kube-burner
      thresholds:
      - conditionType: Ready
        metric: Avg
        threshold: 4s


jobs:
  - name: kubelet-density
    jobIterations: 550
    qps: 20
    burst: 20
    namespacedIterations: false
    namespace: kubelet-density-heavy
    waitWhenFinished: false
    podWait: true
    objects:
      - objectTemplate: /var/configs/templates/postgres-deployment.yml
        replicas: 1

      - objectTemplate: /var/configs/templates/app-deployment.yml
        replicas: 1
        inputVars:
          readinessPeriod: 10

      - objectTemplate: /var/configs/templates/postgres-service.yml
        replicas: 1
