apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: burner
spec:
  machineConfigSelector:
    matchExpressions:
      - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker,burner]}
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/burner: ""
